import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import StyledJsxRegistry from './registry'
import { GlobalStyles } from './globals'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <title>UAP Reports</title>
      </head>
      <body className={inter.className}>
        <StyledJsxRegistry>
          <GlobalStyles />
          {children}
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
